core/urls.py
from os import name
from django.urls import path
from . import views

app_name = "core"
urlpatterns=[
    path('', views.index, name='index'),
    path('yourstory', views.yourstory, name="yourstory"),
    path('hackernews',views.hackernews,name='hackernews'),
    path('about',views.about,name='about'),
]

scraper/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
]

core/models.py
from django.db import models
from django.forms import widgets

# Create your models here.

class UserFeedback(models.Model):
    name=models.CharField(max_length=70)
    email=models.EmailField(max_length=40)
    feedback=models.CharField(max_length=800)
    date = models.DateTimeField("Date")

    def __str__(self):
        return f'{self.name}:: {self.feedback}'

core/forms.py
from django import forms
from django.forms import fields, widgets
from .models import UserFeedback

class Feedback(forms.ModelForm):
    class Meta:
        model=UserFeedback
        fields=['name','email','feedback']
        labels={'email':'Enter Email','feedback':'Write feedback','name':'Enter name'}
        widgets={'name':forms.TextInput(attrs={'class':'form-control'}),'email':forms.TextInput(attrs={'class':'form-control'}),'feedback':forms.Textarea(attrs={'class':'form-control'})}
    

core/views.py
from django.shortcuts import render
import requests
from bs4 import BeautifulSoup
from urllib.request import urlopen
import datetime

from django.utils import timezone

from .forms import Feedback
from .models import UserFeedback
from django.http import HttpResponse

def yourstory(request):
    l = []
    url = 'https://yourstory.com/feed'
    content = requests.get(url).content
    soup = BeautifulSoup(content, "html.parser")
    for n, t in enumerate(soup.findAll("title")):
        l.append(str(n) + " - " + t.text)
    l.pop(0)
    todays_date = datetime.datetime.now()
    return render(request,'core/yourstory.html',{'links':l,'date':todays_date})

def hackernews(request):
    url='https://news.ycombinator.com/'
    l=[]
    content = urlopen(url).read()
    soup = BeautifulSoup(content,'html.parser')
    for i,tag in enumerate(soup.find_all('td',attrs={'class':'title','valign':''})):
        l.append(str(i+1)+' - '+tag.text + '\n') if tag.text!='More' else ''
    todays_date = datetime.datetime.now()
    return render(request,'core/hackernews.html',{'links':l,'date':todays_date})
       

def index(request):
    return render(request, 'core/landing.html')

def about(request):

    if request.method=="POST":
        feedback_obj=Feedback(request.POST)
        if feedback_obj.is_valid():
            name_val=feedback_obj.cleaned_data['name']
            email_val=feedback_obj.cleaned_data['email']
            feedback_val=feedback_obj.cleaned_data['feedback']
            UserFeedback_obj=UserFeedback(email=email_val,feedback=feedback_val,name=name_val,date=timezone.now())
            UserFeedback_obj.save()
            feedback_obj=Feedback()
            
    else:
        feedback_obj=Feedback()
    latest_feedback_list = UserFeedback.objects.order_by("-date")[:5]
    return render(request,'core/about.html',{
        'form':feedback_obj,
        'latest_feedback':latest_feedback_list
    })

core/templates/core/about.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}
<div class="container">
<p class="fs-1">About us</p>

<p>
    This web application provides you with the latest news headlines of hackernews.com and yourstory.com with
    preciseness.
    Every headline present here is efficient and up-to-date as per the parent websites.
    The technology used in this web application is Django (python web framework) with beautiful Soup (python pakage) used
    for scraping.
    Purpose -
    This application purposely made to save the precious time of an individual as it serves the header of the news and
    keep you up-to-date in a very short time.
</p>
<p class="fs-4">HackerNews</p>
<p>
    Hacker News is a social news website focusing on computer science and
    entrepreneurship. It is run by Paul Graham's investment fund and startup incubator, Y Combinator. In general, content that can be
    submitted is defined as "anything that gratifies one's intellectual curiosity.
</p>
<p class="fs-4">YourStory</p>
<p>
    The YourStory Team brings you stories of entrepreneurs and change-makers, funding analyses, resource pieces and the first glimpse of emerging trends from India's entrepreneurial ecosystem, as well as profiles of great businesses and entrepreneurs from all over the world.
</p>
</div>

<div class="container">

    <div class="border border-secondary border-2 p-4">
        <p class="fs-2">
            Give your valueable feedback here
        </p>

        <form action="" method="POST">
            {% csrf_token %}

            {{form.as_p}}

            <input type="submit" value="Submit" class="btn btn-primary">
        </form>
    </div>

    <div class="">
        <div class="fs-4 fw-bold my-3 text-center">Reviews</div>
            {% for latest in latest_feedback %}
                <div class="my-3 d-flex justify-content-center" type="none">
                    <div class="card alert alert-success fw-bold w-75">
                        <div class="card-body">
                          <p class="card-text">{{latest}}</p>
                        </div>
                      </div>
                    </div>
            {% endfor %}
      
    </div>
</div>

{% endblock content %}

core/templates/core/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'core/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'core/css/style.css' %}">
    <title>Document</title>
    <style>

        .ulljulul{
            padding-top: 40%;
        }
        .ulljulul a{
            margin: 10px;
        }
        .page-footer{
            background-color:#f3f3f2;
            padding-top:50px;
            padding-bottom:10px
        }
        .page-footer h4{
            color:#333;
            font-size:11px;
            font-weight:700
        }
        .page-footer p{
            text-align: center;
            color:#888;
            font-size:11px
        }
        .page-footer .footer-links{
            list-style:none;
            padding:0;
            margin-bottom:45px;
            word-break:break-all
        }
        .page-footer .footer-links a,.page-footer .region a{
            color:#555;font-size:11px
        }
        .page-footer .footer-links li{
            margin-bottom:5px;
            line-height:1.3
        }
        .page-footer .footer-legal .copyright{
            margin-right:60px
        }
        .page-footer .footer-legal .legal-links .item{
            padding-right:13px;
            border-right:1px solid #ccc;
            margin:0 13px 0 0
        }
        .page-footer .footer-legal .legal-links .item:last-child{
            border-right:none
        }
        .page-footer .footer-legal .legal-links .item h5{
            font-size:11px;
            margin-top:0;
            margin-bottom:0
        }
        .page-footer .region{
            margin-bottom:20px
        }
        .page-footer .region img{
            margin-right:7px
        }
        @media (min-width:768px){
            .page-footer .region{
                margin-bottom:0
            }
        }
    </style>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #e3f2fd;">
        <div class="container-fluid">

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item fs-3 fw-bold">
                        <a class="nav-link active" aria-current="page" href="{% url 'core:index' %}"><img src="{% static 'core/images/Copy of News.png' %}" width="120px" style="margin-left: 20px;"></a>
                    </li>
                </ul>
                <div class="d-flex fs-5 fw-bold">
                    <a class="nav-link" href="{% url 'core:index' %}">Home</a>
                    <a class="nav-link" href="{% url 'core:hackernews' %}">Hacker News</a>
                    <a class="nav-link" href="{% url 'core:yourstory' %}">Your Story</a>
                    <a class="nav-link" href="{% url 'core:about' %}">About</a>
                </div>
            </div>
        </div>
    </nav>

    {% block content %}

    {% endblock content %}

    <footer class="page-footer">
            <div class="container">
{#                <div class="row">#}
{#                    <div class="col-6 col-md-3">#}
{#                        <h4>Shop and Learn</h4>#}
{#                        <ul class="footer-links">#}
{#                            <li><a href="#">Makbuk</a></li>#}
{#                            <li><a href="#">iFhone</a></li>#}
{#                            <li><a href="#">iFad</a></li>#}
{#                            <li><a href="#">iBaatch</a></li>#}
{#                            <li><a href="#">iMusik</a></li>#}
{#                            <li></li>#}
{#                        </ul>#}
{#                    </div>#}
{#                    <div class="col-6 col-md-3">#}
{#                        <h4>DoubleApple Nearest Shop</h4>#}
{#                        <div>#}
{#                            <p>#}
{#                                <span style="text-decoration: underline;">Shaitan Gali, Khatra Mehal <br>,Andher Nagar, Samshan ke samne.</span>#}
{#                            </p>#}
{#                        </div>#}
{#                    </div>#}
{#                    <div class="col-6 col-md-3">#}
{#                        <h4>For Education</h4>#}
{#                        <ul class="footer-links">#}
{#                            <li><a href="#">Shop for Education</a></li>#}
{#                            <li><a href="#">Shop for University</a></li>#}
{#                        </ul>#}
{#                        <h4>For Business</h4>#}
{#                        <ul class="footer-links">#}
{#                            <li><a href="#">DoubleApple and Business</a></li>#}
{#                            <li></li>#}
{#                        </ul>#}
{#                    </div>#}
{#                    <div class="col-6 col-md-3">#}
{#                        <h4>Account</h4>#}
{#                        <ul class="footer-links">#}
{#                            <li><a href="#">Manage Your Double Apple Id</a></li>#}
{#                            <li><a href="#">iKloud.com</a></li>#}
{#                        </ul>#}
{#                        <h4>About DoubleApple</h4>#}
{#                        <ul class="footer-links">#}
{#                            <li><a href="#">Newsroom</a></li>#}
{#                            <li><a href="">Contact DoubleApple</a></li>#}
{#                        </ul>#}
{#                    </div>#}
{#                </div>#}
                <p>All the designing are made by taking apple website as a reference.Made by <em>Our Team</em>.</p>
                <hr>
                <div class="footer-legal">
                    <div class="float-md-right region">
                        <a href="#">India</a>
                    </div>
                    <div class="d-inline-block copyright">
                        <p class="d-inline-block">Copyright © 2021.<br></p>
                    </div>
                    <div class="d-inline-block legal-links">
                        <div class="d-inline-block item">
                            <h5>Privacy Policy</h5>
                        </div>
                        <div class="d-inline-block item">
                            <h5>Terms of Use</h5>
                        </div>
                        <div class="d-inline-block item">
                            <h5>Legal</h5>
                        </div>
                        <div class="d-inline-block item">
                            <h5>License</h5>
                        </div>
                    </div>
                </div>
            </div>
    </footer>


    <script src="{% static 'core/js/jquery.js' %}"></script>
    <script src="{% static 'core/js/popper.js' %}"></script>
    <script src="{% static 'core/js/bootstrap.min.js' %}"></script>


</body>

</html>

core/templates/core/hackernews.html
{% extends 'core/base.html' %}

{% block content %}
<div class="container">
    <header class="mt-4">
        <div class="alert bg-warning bg-gradient text-dark text-center" role="alert">
            <p class="alert-heading fs-1 fw-bold">Hacker News</p>
            <div class="fw-bold">{{date|date:'d M Y'}}</div>
            <hr>
            <p class="mb-0 fw-bold">In a nutshell...</p>
        </div>
    </header>
    <div class="">
        <ul class="list-group list-group-flush"></ul>
        {% for link in links %}

        <li class="list-group-item fs-4 fw-bold">
            <div class="p-2">{{link}}</div>
        </li>

        {% endfor %}
        </ul>
    </div>
</div>

{% endblock content %}

core/templates/core/landing.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}

<header>
    <div class="ps-4">
        <div class="fs-1 mt-4">Looking for news headlines??</div>
        <div class="fs-3 text-muted">There you go....</div>
    </div>

</header>
<div class="container">
    <div class="row">
        <div class="col uljulul">
            <div class="">
                <img src="{% static 'core/images/news1.jpg' %}" alt="image" class="img-fluid" width="550">
            </div>
        </div>
        <div class="col">
            <div class="d-grid gap-2 ulljulul">
                <a href="{% url 'core:hackernews' %}" class="btn btn-warning btn-lg" tabindex="-1" role="button" aria-disabled="true">HackerNews</a>
                <a href="{% url 'core:yourstory' %}" class="btn btn-info btn-lg" tabindex="-1" role="button" aria-disabled="true">Yourstory</a>
            </div>
        </div>

    </div>
</div>




{% endblock content %}

core/templates/core/yourstory.html
{% extends 'core/base.html' %}

{% block content %}


<div class="container">
    <header class="mt-4">
        <div class="alert bg-info bg-gradient text-dark text-center" role="alert">
            <p class="alert-heading fs-1 fw-bold">Your story</p>
            <div class="fw-bold">{{date|date:'d M Y'}}</div>
            <hr>
            <p class="mb-0 fw-bold">In a nutshell...</p>
        </div>
    </header>
    <div class="">
        <ul class="list-group list-group-flush"></ul>
        {% for link in links %}

        <li class="list-group-item fs-4 fw-bold">
            <div class="p-2">{{link}}</div>
        </li>

        {% endfor %}
        </ul>
    </div>
</div>

{% endblock content %}